apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: crud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: final_assignment-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: db_address
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_ADDRESS
            - name: db_username
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_USERNAME
            - name:  db_name
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_DBNAME
            - name:  db_password
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_DBPASSWORD
