apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
        containers:
          - name: backend
            image: final_assignment-backend:latest
            imagePullPolicy: Never
            ports:
                - containerPort: 8000
            env:
                - name: db_address
                  value: db
                - name: db_username
                  value: postgres
                - name:  db_name
                  value: postgres  
                - name:  db_password
                  valueFrom:
                      secretKeyRef:
                        name: db-secrets
                        key: POSTGRES_DBPASSWORD
      
                        
    
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
        
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
    type: ClusterIP
    selector:
      app: db
    ports:
      - port: 5432
        targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
    selector:
        matchLabels:
          app: db
    template:
        metadata:
          labels:
            app: db
        spec:
            containers:
            - name: db
              image: postgres:16
              ports:
                  - containerPort: 5432
              env:
                - name: POSTGRES_DB
                  value: postgres
                - name: POSTGRES_USER
                  value: postgres
                - name: POSTGRES_PASSWORD
                  valueFrom:
                      secretKeyRef:
                        name: db-secrets
                        key: POSTGRES_DBPASSWORD
                  
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  POSTGRES_DBPASSWORD: QXAwMHJQYSQkdzByZCE=