apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: crud-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  storageClassName: manual