apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: crud-app
spec:
    capacity:
        storage: 500Mi
    accessModes:
        - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    storageClassName: manual
    hostPath: 
      path: /mnt/data/db-pv